[core]
    name = "Bitespeed"
    host = "localhost"
    port = 3000
[database]
    name = "bitespeed"
    host = "host.docker.internal"
    port = 3306
    username = "root"
    password = "password"